# -*- coding: utf-8 -*-
"""Bankrupt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fs9uH1X9GtRm9JSR0W5Mc-LMCy9WmqVQ
"""

import pandas as pd
  df = pd.read_csv("/content/Bankrupt.csv")

df

p1 = df['Bankrupt?'].to_list()

p2 = df[' Operating Gross Margin'].to_list()

p3 = df[' Operating Profit Rate'].to_list()

p4 = df[' Cash flow rate'].to_list()

p5 = df[' Net Value Per Share (A)'].to_list()

p6 = df[' Persistent EPS in the Last Four Seasons'].to_list()

p7 = df[' Total Asset Turnover'].to_list()

p8 = df[' Working Capital to Total Assets'].to_list()

p9 = df[' Current Liability to Assets'].to_list()

p10 = df[' Equity to Liability'].to_list()

# Importing library
from scipy.stats import f_oneway

# Conduct the one-way ANOVA
f_oneway(p1, p2, p3, p4, p5, p6, p7, p8, p9,p10)

